FROM scratch
LABEL org.entando.bundle-name="hackathon-2023-ng-spring"
ADD .entando/output/descriptors/ .
ADD microfrontends/form-renderer/dist/form-renderer widgets/form-renderer
ADD microfrontends/form-generator/dist/form-generator widgets/form-generator
